---
title: "Text of Paper"
format: html
editor: visual
---

## Academic Writing Sample

#### Social Media and the Israel-Hamas War

Read it as a pdf here.

Nobody understood the extent of the carnage. A missile reportedly collided into a hospital in the Gaza Strip, slaughtering hundreds of Palestinians who likely flocked to the facility to find refuge. Immediately after the strike, Palestinian officials, controlled by the militant group Hamas, blamed Israel for the deadly strike. Israel then flipped the blame onto Palestine, accusing their misfired rocket of causing the devastating blast. As the dust settled in the hours after the explosion, it seemed like nobody, including governments, the media, and most of all, the public, had a clear picture as to who fired the rocket. 

But on the internet, it didn\'t matter. Individual accounts began exchanging accusations about who fired the missile. On social media, where false claims can spread faster than verified information, theories began to move as both sides plead their case to a virtual audience. The Israel Defense Force published a video of the missiles to show it was a Palestinian rocket, only for them to take the video down after a New York Times journalist noted the video\'s timestamp was marked after the reported explosion (Bond, 2023). Hamas turned to Telegram to blame Israel, also accusing Western states of being guilty of \"genocide\" (Harwell and Dwoskin, 2023). A Twitter account claiming to be a journalist from Al Jazeera said they were an eyewitness to the explosion, adding that the hospital was hit by a Hamas rocket. Al Jazeera repudiated the account \-- which has since been removed from Twitter \-- but the seemingly erroneous claims were still widely circulated, and the account\'s followers spiked (Bond, 2023). \"Israel just bombed the Baptist Hospital, killing 500 Palestinians,\" Michigan Congresswoman Rashida Tlaib tweeted. Digital headlines from media publications, including the New York Times, quoted Hamas and said the rocket was fired from Israel, only for the Times to change the headline later to take a more neutral tone (New York Times, 2023). The competing claims bounced against one another online as pro-Israel and pro-Palestine groups commandeered different statements to fit their conflicting narratives. All this to say \-- in the immediate wake of the hospital\'s deadly rocket attack, arguably the most tense and critical moment in the war yet \-- nobody knew what was going on, much less social media. 

Still, in today\'s age, the internet is where information spreads easiest and fastest \-- there is unlimited virality potential in any video, post, or image. And Israel and Hamas are among \"a growing trend of governments around the world moving aggressively online in order to shape their image, especially in times of crisis\" (Martin, Goujard, and Fuchs, 2023). Ultimately, independent reports and visual analysis confirmed a few days after the missile that struck the hospital was likely a misfired rocket that originated in Palestine. But the damage was done. By the time it was independently confirmed, the narratives around who fired the rocket had already impacted international decision-making. Leaders of Jordan and Egypt canceled a sitdown with President Biden (Yee, 2023). Protests erupted in the Middle East (Yee, 2023). The reverberations of the initial reports illustrate a wider trend in 21st-century wars, which are reaching a head in the Israel-Palestine escalation \-- the internet has become a new battlefield. 

Israel and Palestine have begun using social media to wage wars for information, vying to erode trust, harness fear, and rally the public to a cause through their online social communication networks. While the public previously digested wars through the traditional T.V., print, and radio media, \"today, it is those doing the fighting or those caught up in it who produce its fastest-moving images, as soldiers and civilians alike film conflicts and distribute their acts of witness or advocacy\" (Farago, 2023). In the race for aid and public opinion, social media puts the Israel and Hamas war in charge of the propaganda machines. Both sides have produced bloody, graphic images that they use online to rally their supporters and garner support, all in the hopes of winning the war. The effect is two different, largely uncontested views on reality, where it becomes less clear what\'s right and more clear who is wrong. 

In the wake of Hamas\' brutal attack on Israel, where the militant group killed 1,400 people and injured 3,400 more in Israel (ABC News, 2023), the Israeli government turned to social media to show the scope and brutality of the attack, pleading their case for assistance. Israel started pushing ads that display \"brutal and emotional imagery of the deadly militant violence\" on Twitter and YouTube (Martin, Goujard, and Fuchs, 2023). Those ads were predominantly directed at a Western audience, with Israel focusing its online markets in the European Union and the United States. Images of bloodied elderly, youth, and babies \"murdered and burned\" circulated on Twitter and into the psyches of the public. One Israeli ad asks other parents to sympathize with the parents of dead Israeli children, asking how they would react in the crisis. Israel also targeted images toward U.S. officials, like Secretary of State Anthony Blinken, who was shown images of dead babies (Klimento, 2023). The United States and the United Nations classify Hamas as a terrorist group, and Israel is using social media to highlight how that terror is affecting Israelis who are still reeling from the incursion. Showing these images, paid for by the Israeli Foreign Affairs Ministry (Martin, Goujard, and Fuchs, 2023), to the Western public and Western leaders builds sympathy for the victims of the Hamas attack. No longer are the deaths some abstract consequence or statistic, but they\'re gruesome and take up space in your most intimate belonging, your phone. The tactic aims to reinforce the public and official alliance with Israel by vilifying the actions of Hamas. \"The world defeated ISIS. The world will defeat Hamas,\" one ad reads (Martin, Goujard and Fuchs, 2023).  

Conversely, Hamas is using social media to strike terror. Upon their attack into Israel, the group began uploading visceral images of dead and mutilated bodies, live executions, and Hamas celebrating the attack in the homes of dead Israelis (Frenkel and Minsberg, 2023). \"Time for photographs,\" one militant said while pointing the camera at a dead body (Harwell and Dwoskin, 2023). These images and videos were largely uploaded onto Telegram, where content moderation is weaker, and Hamas can circulate its videos. Unlike Facebook, Twitter, or TikTok, where Hamas is banned and where there are some \-- though often feeble \-- moderation attempts, Telegram lets anyone circulate videos online, even if they include the ravaged bodies of dead Israelis. \"Hamas\'s social media strategy was evident in the initial hours of its bloody assault when visceral footage from body-worn GoPro cameras quickly flooded its Telegram channels\" (Harwell and Dwoskin, 2023). These gruesome videos would often jump from Telegram and then begin circulating on Twitter for more eyes to see. In some instances, Hamas militants made their way into the personal social media accounts of their civilian victims and filmed the dead bodies of the account\'s owner or family (Harwell and Dwoskin, 2023). These images add to the fear of the attack. For Israelis, Hamas drove on their roads. They were in their backyards. Their kitchens. Their living rooms. Their phones. Their home. Hamas used the gore to strike fear into the minds of Israelis, and then they posted it all online. Some of the images posted to Telegram were accompanied by fundraising donations, where they sought donations in cryptocurrency (Harwell and Dwoskin, 2023). Hamas was capitalizing on the world\'s focus on them. Izzedine al-Qassam Brigades, their military wing, following on Telegram, grew by more than 200,000, now sitting at 700,000 followers (Harwell and Dwoskin, 2023). Gaza Now, a media outlet linked to Hamas, urged its 1.4 million supporters to take action (Harwell and Dwoskin, 2023). While the onslaught on the ground was unimaginable, Hamas used the limitless nature of the internet to spread its message far past the bounds of the region. Pro-Hamas actors and neo-nazi extremists in the U.S. used the war to post to social media and call for attacks against Jewish communities (Dilanian, Ainsley, Winter and Dienst, 2023). 

The social media strategies from Israel and Hamas extended the battlefront outside of Israel and Gaza and into the personal phones, laptops, and accounts of people living around the world. Both Israel and Hamas have a \"\'dream of the perfect camera.\' Each believed that cheap digital kits (or sophisticated surveillance apparatuses) would allow it to leapfrog the mass media or its political opponents, and to finally deliver the transparency that would confirm its own view of the conflict.\" (Farago, 2023) While Israel used their digital ad campaign to cultivate sympathy, Hamas used the platform to foster terror. Though different in form, both methods were aimed at becoming the perfect image to sway the general public onto their side. Israel and Hamas understand that roughly half the population gets its news from social media (Pew Research, 2021), which means that the neverending battle for public opinion can be helmed by the very organizations fighting the war, rather than the media organizations covering it. They don\'t have to go through a third party anymore. They can do it themselves. Israel and Hamas have turned to pushing their agenda through social media, no matter how graphic. Who is going to stop them? 

Online content moderators have struggled to stay on top of the onslaught of information as both Israel, Hamas, and witnesses to the war have posted waves of gruesome imagery online. The war has exacerbated existing issues over content moderation on social media platforms, where erroneous or graphic posts are widely circulated before they have the chance to be fact-checked, flagged, or removed from a platform. While Facebook, Instagram, or TikTok have tougher policies, Telegram is more lenient with its content moderation, so more goes (Thompson and Isaac, 2023). Twitter, now known as X, has removed much of its content moderation team since Elon Musk took over the platform, meaning more crude content can jump from one site to another and appear on the phones of individuals not seeking out the information (Kern, 2023). For many, the war has inundated users with so much information to sludge through that it becomes difficult to discern what is real and what\'s fake. The difference is even trickier for users as fake claims can spread online just as quickly as credible ones. Doctored images and videos have made their way online. One lifelike clip alleged Hamas fighters shot down an Israeli helicopter, but it\'s a video from a video game (Bond, 2023). \"Many online videos are being taken out of context or mischaracterized --- a frequent occurrence in breaking news situations where interest is high but verified information is hard to come by.\" (Bond, 2023). 

There has also been an inconsistent response to these issues from the West. The European Union has strict moderation policies. They passed the Digital Services Act to warn X, Meta, TikTok, and YouTube for its handling of violent content and disinformation surrounding the war. But the United States social media is faltering \-- the First Amendment, an unregulated internet ecosystem, and Section 230 of the 1996 Communications Decency Act, which protects social media companies from liability over the information they disseminate, limits the power government officials have to fight against harmful posts (Kern, 2023). Legislators and the White House have repeatedly asked some platforms like Twitter to raise questions about the social media\'s practices. \"We are in regular dialogue with the tech platforms on these issues of responsible behavior at a volatile time,\" a White House official told POLITICO (Kern, 2023). Because U.S. legislators have been slow to the punch on regulating social media \-- unlike their European counterparts \-- the U.S. public is receiving more erroneous information. The unregulated nature of the U.S. social media ecosystem is putting more suspect information in the hands of users at never-before-seen rates. 

Social media democratized the information system by lowering the barriers necessary to collect, distill, and disseminate information. In the Israel-Hamas war, that means both Hamas and Israeli governments have equal access to spread information without the need for a traditional media source. They\'ve both used the mechanism to further their respective agendas by publishing horrific images of blood, death, and war. Those images, while from the front lines \-- some offering a glimpse into the horrors that have come from the war \-- are also against the very policies of the social media platforms they are being posted to, so moderators try to remove them as fast as they go up (Kern, 2023). But unlike the traditional media, where journalists and editors can slow down the process and act as barriers to prevent graphic information from being published, there are no guardrails between a personal post going viral. Coupled with a slew of new content being uploaded, downloaded, and shared every day, the poor moderation mechanisms are also leading to the spread of mis and disinformation. That harmful information \-- which can move just as quickly as helpful information \-- has confused readers and oftentimes left the public with vast takeaways about what\'s really happening in the war. \"It\'s tragic. X is a high-speech information-blender pureeing facts and news and minds into mush during major world events. And the effect is massive confusion with potentially disastrous results,\" Conde Nast legal affairs editor Luke Zaleski wrote (Stetler, 2023).  

In all the ruckus of social media, news agencies have taken on more rolls as information, and the methods used to gather it have expanded. Traditional news media were the sole voice on war coverage \-- Iraq, Vietnam, Korea, and WWII all had focused reporters, and the public disseminated the news about them through the media. But now, as trust in the media erodes, individuals are turning to news on social media, where misinformation and misleading claims purported by Israel and Hamas blend together. That\'s why the media is taking a new approach. On top of their regular war coverage, media organizations are fact-checking incorrect claims made online. Reuters has spent entire articles fact-checking misinformation from both Israel and Hamas online, checking captions, videos, and official statements (Kennedy, 2023). Other reporters are asking tough questions from officials to ensure misinformation that spreads online does not become \'news\' that informs policy. Claims that Hamas beheaded babies were widely circulated online. Israel initially confirmed the reports. President Biden went on to say he saw beheaded babies after the attack on Gaza, per Israeli intelligence. But further probing from the media found there were no beheaded babies, and Israel and Biden got it wrong (Dwoskin, 2023). Other media outlets are using their new \'visual investigations teams\' to analyze images and find the truth of what\'s real and what isn\'t on the internet. The strongest case so far has been a New York Times investigation into the hospital missile. They found that a video of a rogue missile by Al Jazeera, which U.S. and Israeli intelligence cited to back their claims that it was a Hamas missile, was likely an Israeli missile, drawing into question the widely circulated claims (Toler et. al., 2023). Analyzing misinformation can help the public better understand what\'s real and what\'s fake. Seeing social media as a tool, rather than the enemy, can help news agencies discern what information to process and include as both sides of the war have begun to weaponize the resource. 

Despite all the harm that has come from social media, the power of more people having a voice that can enter the mainstream has been beneficial for people on the ground who have historically been ignored. Palestinian TikTokers are trying to contextualize the war through explanation videos that can give first-person accounts of the history and personal narratives behind the complex dispute (Lorenz, 2023). Sarah Warah used TikTok to dive into her life in a refugee camp in the occupied West Bank. She explains her views on the subject and what her experience has been like living through the conflict (Lorenz, 2023). Adnan Barq, a Palestinian TikToker, has been countering media narratives with his \"Mute the Media\" series, where he tries to build trust that has been lost by traditional media (Lorenz, 2023). These examples on social media are about providing a new perspective on the war, separate from the voices of Israel and Hamas and the mainstream media. People in Israel also used social media, the platform WeAreOneIsrael, to connect victims with information, resources, and assistance in the immediate fallout of the attack by Hamas (Frenkel and Minsberg, 2023). These resources helped bring people together and were made easier by the lowered barrier of communication in media. People could help people. However, these examples mark stark contrasts to the social media practices of both Israel and Hamas. While the two groups primarily used social media to spread violence and the imagery that came along with it for political messaging, these individuals are taking on social media and using it to provide a resource for others. 

Social media has evolved the way parties, the public and mainstream news ingests and processes information. Particularly by flattening the participation model so that everyone has the potential for a viral voice. Israel and Hamas used that potential to spread similar but opposing messages. Israel tried to garner sympathy for its cause, while Hamas tried to push fear while bringing their violence to a global scale. In return, both parties have gained more followers as Israel sympathizers and Hamas apologists have exploded onto the scene in support of both groups. Their messages were able to circumvent traditional media styles and content moderation concerns on social media to expand their reach. Their ability to spread information has also caused confusion at critical points like the missile attack and stoked distrust as misinformation spreads and people begin to be dehumanized through the oversaturation of violence. Conversely, other groups have taken the ease of social media to spread their own messages, like finding support and aid in the war, or creating space for their own experiences in Israel, Palestine, and in other parts around the world to flourish into the mainstream conversations. Each side illustrates a way social media presents a new battlefront as it alters how war is covered, talked about, and experienced by the people living in it. 

While U.S. and Israeli officials have now cemented their positions that the hospital missile was shot from Gaza, independent reports from witnesses on the scene and news outlets have muddied any clear answers as to who fired the bomb (Bruell, 2023). Still, despite new and mixed evidence coming out after the explosion, it doesn\'t seem to matter. After reports of the missile first came out, people had already made up their minds about who fired it and what happened, largely thanks to social media. They\'re sticking to their guns. And while officials may eventually find out who fired the deadly missile, one thing is clear, due to the immediate influence social media had on the public, it may not matter. 
