---
title: "News Writing"
format: html
editor: visual
---

## News Writing Sample

#### We Hung Out All Day Outside the Trump Arraignment

*Read it online [here](https://www.washingtonian.com/2023/08/04/we-hung-out-all-day-outside-the-trump-arraignment/). Or, read on.*

\--

Not long after I arrived at the E. Barrett Prettyman Courthouse at 10:15 AM on the morning of August 3, I spotted a double-decker tour bus that had slowed so its occupants could snap photos. It wasn't clear if any of them knew what would be happening here later in the day: the historic arraignment of former president Donald Trump. But it must have been obvious that *something* was brewing. Though Trump's arrival was still hours away, the area was crawling with journalists. There were tents filled with cameras, microphones, and other miscellaneous TV equipment. Broadcast trucks with satellite dishes stood ready to beam out reports, while some networks also erected metal fences or brought along security guards to prevent the public from entering their designated areas. "It feels like a reality TV show," said one passerby.

Prior to Trump's arrival, much of the media focus was on the small but vocal bunch of [protestors who had assembled---some of them to support Trump and others to heckle him](https://www.washingtonian.com/2023/08/03/trumps-arraignment-the-scene-outside-the-dc-courthouse/). Among the most outspoken was a guy named Steve Corson, who, about two and a half years earlier, had been one of the thousands of Trump supporters who marched to the Capitol. Corson, wearing a "We the People Hat," used his left hand to wave a pole adorned with two flags---a US flag on top and a "Don't tread On Me" banner on the bottom. "I was hoping there'd be thousands out here," he said, holding a "Free J6ers" sign in his right hand. At that point it was still morning, and there were just a smattering of protestors. More would appear later on, though the crowd appeared to skew more anti-Trump than pro.

Throughout the day, Corson proved to be a popular source for the assembled media: He was interviewed by a number of news organizations, including *USA Today* and the *Washington Post*, which actually quoted him in [two separate](https://www.washingtonpost.com/national-security/2023/08/03/trump-indictment-violence/) [reports](https://www.washingtonpost.com/dc-md-va/2023/08/03/dc-courthouse-scene-trump-arraignment/). (He also provided me with some genuinely useful advice: Cross the street to use the National Portrait Gallery bathrooms instead of the putrid-smelling portable toilets provided outside the courthouse. I took him up on it.)

Elsewhere, a man ran around in an inflatable yellow Trump suit with a "loser" sign on it, crying that "I can't go to jail!" (He said he bought the suit in Pentagon City). A dude wearing devilish goat horns meandered from place to place to yell about...I'm not entirely sure what (a frequent situation, it must be said). There was a huge inflatable scab rat with Trump's face on it, which a tourist from Baltimore asked me to take his picture in front of. And some smart opportunist was promoting a Trump merch website while waving a Trump/Godfather mashup flag [that'll put you back \$20](https://www.trumpswag.com/product/donafather/79?cs=true&cst=custom). "Do these people have jobs?" I heard one journalist say to his colleague.

If all of that sounds exciting, well, it really wasn't. For hours, nothing much happened. Tourists continued to walk by the courthouse, either for a quick selfie or to ask what was happening while on their way to  the Capitol or National Portrait Gallery. To pass the time before Trump's arrival, I made laps around the courthouse. Police officers reclined against walls or sat in their cars. Later in the day, Park Police rode in on horses. On the east side of the building, photographers set up ladders in hopes of getting a glimpse of Trump as he drove into the courtroom. Some people streamed the scene live on Instagram or TikTok. There was also a dead rat sprawled on the sidewalk---its eyes still open. [Welcome to DC](https://www.washingtonian.com/2018/09/02/the-rats-are-taking-over-dc/).

As we got closer to Trump's arrival, more and more people appeared. The scene began to resemble the two prior Trump arraignments in [New York](https://www.reuters.com/world/us/trump-supporters-detractors-crowd-around-manhattan-courthouse-ahead-arraignment-2023-04-04/) and [Miami](https://www.politico.com/news/2023/06/13/trump-supporters-begin-descending-on-miami-courthouse-amid-circus-like-atmosphere-00101721). Pro- and anti-Trump protestors would argue, which escalated into screaming bouts, usually attracting a group of onlookers who'd take out their phones to record. These ongoing vocal skirmishes were so distracting that hardly anyone noticed when Trump finally arrived at the courthouse, especially since he used a private entrance. As the former Commander-in-Chief headed for processing, a guy outside was running around in a Jar Jar Binks mask. The smell of weed occasionally wafted through the air.

Once word spread that Trump had arrived, people started to line up along the road behind the courthouse in hopes of catching a glimpse when his motorcade departed. The Secret Service stood guard and men in military-ish uniforms popped up on the roof above the courthouse, scanning the crowd that had gathered along a fence blocking the road. Then, without any warning, the motorcade was driving away. The crowd turned and began to chase. I'm not sure if anyone waiting outside even caught a glimpse of the former president. I certainly did not.

At that point, the crowd mostly left, almost as quickly as Trump. Within 20 minutes, the hundreds of people that had swirled around the courthouse were nearly gone, leaving a few straggling media tents and onlookers behind. Was braving the whole spectacle worth it? I talked to a mother and son, Kathleen and Patrick Rhinehart, who live in New Mexico and happened to be in town visiting family. "We wanted to see, it's so important," Kathleen said. "People want to see history happening. I'm glad I'm here."
